### ISSUE TITLE
add @orbeckst to maintainers

### ISSUE THREAD

**Issue by orbeckst** [conda-forge/numkit-feedstock#3]
### Comment:

@njzjz can you please add me as a maintainer to the feedstock? Then I can quickly fix up the 1.3.0 regro-cf PR #2 . Thanks.

(For context: I am the main developer of https://github.com/Becksteinlab/numkit )

**Comment by njzjz** [comment]
@conda-forge-admin, please add user @orbeckst

**Comment by orbeckst** [comment]
Thank you. I agree to be a maintainer on the feedstock.
